[package]
name = "molbloom"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.22", features = ["derive", "env"] }
fastbloom = { version = "0.8.0", features = ["serde"] }
serde_json = "1.0"
anyhow = "1"
